### PR TITLE
Enable experimental alt text attribute, bump versions, add new debug mode for local coding

### PR DESCRIPTION
**Pull request by capjamesg**
This PR includes three changes:

1. Enable the experimental `img_with_alt=True` attribute to allow this website to send alt texts. More context on this feature is available in the [mf2py Experimental features](https://github.com/microformats/mf2py#experimental-features) documentation.
2. Bumps the version for most packages and the Python runtime. This PR moves the project to use Python 3.9 instead of Python 2.
3. Adds a `--debug` optional command line parameter to the `app.py` file. This will aid contributors with local debugging.

I deployed my PR onto a blank Heroku environment to make sure everything works, which you can test below:

https://mf2pyonline.herokuapp.com/

### CODE REVIEW

**Review by tantek — APPROVED** [review]
While this seems ok as an update, I would have preferred if the cleanup/codestyle aspects (different quotes, different lines for parentheses, different line breaks for conditional clauses, etc.) were done in a separate PR either before/after so it was easier to review functional changes separate from cosmetic/stylistic changes.

**Comment by jalcine** [comment]
Seconding [https://github.com/microformats/microformats-parser-website-python/pull/5#pullrequestreview-1116139355](https://github.com/microformats/microformats-parser-website-python/pull/5#pullrequestreview-1116139355) as I think just the bit re: upgrading to Python 3.9 will close [https://github.com/microformats/microformats-parser-website-python/issues/7](https://github.com/microformats/microformats-parser-website-python/issues/7).

(Originally published at: https://jacky.wtf/2022/12/9DMy)

**Comment by snarfed** [comment]
LGTM. Agreed with @tantek that ideally style and functional changes should be separated in the future. Otherwise, ship it!

**Review by kevinmarks — APPROVED** [review]
Updating to python 3.9 makes a lot of sense, and I am taking the library updates on trust

**Pull request merged**
